### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by slokhorst** [adambutler/poll#18]
If I visit https://poll.lab.io/ and enter a question and submit, it says:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

![image](https://user-images.githubusercontent.com/8083666/113285251-07288d00-92eb-11eb-86f7-1fa45f1396a6.png)

**Comment by adambutler** [comment]
Thanks for reporting. I've fixed the problem.
