### ISSUE TITLE
Embed code

### ISSUE THREAD

**Issue by picajoso** [adambutler/poll#7]
Wouldn't it be nice to be able to embed polls and results onto a webpage?

**Comment by adambutler** [comment]
@picajoso iframes are supported... just add this to your site -

```html
<iframe src="http://poll.lab.io/ukb2NQtysb6QUEw4HFF_NQ/results"></iframe>
```

**Comment by picajoso** [comment]
Great!! Maybe a little note on the README for clarification (and for newbies like me) would be a good idea ;) Regards and great job!!
